name: ARGODrifters
channels:
  - conda-forge
  - defaults
dependencies:
#should reproduce the last working environment (from linux system)
#remove version numbers if conflicts
#be cautious about running conda update after. it may break api's 
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - blas=1.1
  - ca-certificates=2018.4.16
  - cached-property=1.4.0
  - cairo=1.14.6
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.2.1
  - curl=7.60.0
  - defusedxml=0.5.0
  - enum34=1.1.6
  - fontconfig=2.12.1
  - freetype=2.7
  - gettext=0.19.8.1
  - glib=2.51.4
  - graphite2=1.3.11
  - harfbuzz=1.4.3
  - hdf4=4.2.13
  - hdf5=1.10.1
  - icu=58.2
  - idna=2.6
  - ipaddress=1.0.22
  - isodate=0.6.0
  - jpeg=9b
  - krb5=1.14.6
  - libffi=3.2.1
  - libiconv=1.15
  - libnetcdf=4.4.1.1
  - libpng=1.6.34
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.1
  - ncurses=5.9
  - numpy=1.14.4
  - openblas=0.2.20
  - openssl=1.0.2o
  - pandas=0.23.0
  - pango=1.40.4
  - pcre=8.41
  - pip=9.0.
  - pixman=0.34.0
  - pycparser=2.18
  - pyopenssl=18.0.0
  - pyqt=4.11.4
  - pysocks=1.6.8
  - python=2.7.15
  - python-dateutil=2.7.3
  - pytz=2018.4
  - qt=4.8.7
  - readline=7.0
  - requests=2.18.4
  - requests-toolbelt=0.8.0
  - setuptools=39.2.0
  - sip=4.18
  - six=1.11.0
  - sqlite=3.20.1
  - tk=8.6.7
  - urllib3=1.22
  - wheel=0.31.0
  - xz=5.2.3
  - zeep=2.4.0
  - zlib=1.2.11
  - intel-openmp=2018.0.3
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - mkl=2018.0.3
### known dependencies
  - cmocean
  - pyyaml
  - netcdf4
