name: ARGODrifters-py36
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - blas=1.1=openblas
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - cached-property=1.4.3
  - certifi=2018.4.16
  - cffi=1.11.5
  - cftime=1.0.0
  - chardet=3.0.4
  - cryptography=2.3
  - cryptography-vectors=2.3
  - curl=7.61.0
  - defusedxml=0.5.0
  - hdf4=4.2.13=0
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.7
  - isodate=0.6.0
  - jpeg=9c
  - krb5=1.14.6
  - libffi=3.2.1
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libssh2=1.8.0
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.3
  - ncurses=6.1
  - netcdf4=1.4.0
  - numpy=1.14.5
  - openblas=0.2.20
  - openssl=1.0.2o
  - pandas=0.23.3
  - pip=18.0
  - pycparser=2.18
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - readline=7.0
  - requests=2.19.1
  - requests-toolbelt=0.8.0
  - setuptools=40.0.0
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.8=0
  - urllib3=1.23
  - wheel=0.31.1
  - xz=5.2.4
  - zeep=2.5.0
  - zlib=1.2.11
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libopenblas=0.2.20
  - libstdcxx-ng=7.2.0
  - numpy-base=1.14.3
  - pyyaml
  - cmocean