name: ARGODrifters
channels:
  - conda-forge
  - defaults
dependencies:
  - netcdf4
  - numpy>=1.14.5
  - python=3
  - zeep
  - pyyaml
  - cmocean
  - spyder
  - matplotlib
  - basemap
  - basemap-data-hires
  - pandas